# Generated by Django 4.1.6 on 2023-02-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('midle_name', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('passport_number', models.CharField(max_length=11, unique=True)),
                ('inn', models.CharField(blank=True, max_length=12)),
                ('snils', models.CharField(blank=True, max_length=11)),
            ],
        ),
    ]
